// ------------------------------------------------------------------------------
//  <auto-generated>
//      Этот код был создан построителем кодированных тестов ИП.
//      Версия: 10.0.0.0
//
//      Изменения, внесенные в этот файл, могут привести к неправильной работе кода и будут
//      утрачены при повторном формировании кода.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestProject_eDoctrinaOcr
{
    using System.CodeDom.Compiler;
    using System.Drawing;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;


    [GeneratedCode("Построитель кодированных тестов ИП", "10.0.40219.415")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinClient uIPictureBox1Client = this.UIEDoctrinaOCREditorv1Window.UIPictureBox1Window.UIPictureBox1Client;
            WinStatusBar uIStatusStrip1StatusBar = this.UIEDoctrinaOCREditorv1Window.UIStatusStrip1Window.UIStatusStrip1StatusBar;
            WinButton uIVerifyButton = this.UIEDoctrinaOCREditorv1Window.UIVerifyWindow.UIVerifyButton;
            WinButton uIRestoreButton = this.UIEDoctrinaOCREditorv1Window.UIRestoreWindow.UIRestoreButton;
            #endregion

            // Переместите  "pictureBox1" клиент из (15, 320) в "statusStrip1" строка состояния (709, 8)
            uIStatusStrip1StatusBar.EnsureClickable(new Point(709, 8));
            Mouse.StartDragging(uIPictureBox1Client, new Point(15, 320));
            Mouse.StopDragging(uIStatusStrip1StatusBar, new Point(709, 8));

            uIVerifyButton.WaitForControlEnabled();
            //UITestControl.WaitForCondition(uIVerifyButton.Enabled,)
            // Щелчок "Verify" кнопка
            Mouse.Click(uIVerifyButton, new Point(43, 10));
           
            uIRestoreButton.WaitForControlEnabled();
            // Переместить  "pictureBox1" клиент из (32, 329) в (389, 600)
            Mouse.StartDragging(uIPictureBox1Client, new Point(32, 329));
            Mouse.StopDragging(uIPictureBox1Client, 357, 271);

            uIVerifyButton.WaitForControlEnabled();
            // Щелчок "Verify" кнопка
            Mouse.Click(uIVerifyButton, new Point(41, 18));

            uIRestoreButton.WaitForControlEnabled();
            // Переместить  "pictureBox1" клиент из (7, 309) в (391, 605)
            Mouse.StartDragging(uIPictureBox1Client, new Point(7, 309));
            Mouse.StopDragging(uIPictureBox1Client, 384, 296);

            uIVerifyButton.WaitForControlEnabled();
            // Щелчок "Verify" кнопка
            Mouse.Click(uIVerifyButton, new Point(27, 15));
        }
        
        #region Properties
        public UIEDoctrinaOCREditorv1Window UIEDoctrinaOCREditorv1Window
        {
            get
            {
                if ((this.mUIEDoctrinaOCREditorv1Window == null))
                {
                    this.mUIEDoctrinaOCREditorv1Window = new UIEDoctrinaOCREditorv1Window();
                }
                return this.mUIEDoctrinaOCREditorv1Window;
            }
        }
        
        public UIEDoctrinaOCREditorSeWindow UIEDoctrinaOCREditorSeWindow
        {
            get
            {
                if ((this.mUIEDoctrinaOCREditorSeWindow == null))
                {
                    this.mUIEDoctrinaOCREditorSeWindow = new UIEDoctrinaOCREditorSeWindow();
                }
                return this.mUIEDoctrinaOCREditorSeWindow;
            }
        }
        
        public UIВыполнениеприложенийWindow UIВыполнениеприложенийWindow
        {
            get
            {
                if ((this.mUIВыполнениеприложенийWindow == null))
                {
                    this.mUIВыполнениеприложенийWindow = new UIВыполнениеприложенийWindow();
                }
                return this.mUIВыполнениеприложенийWindow;
            }
        }
        
        public UIItem8AF085B74DFEFDD3Window UIItem8AF085B74DFEFDD3Window
        {
            get
            {
                if ((this.mUIItem8AF085B74DFEFDD3Window == null))
                {
                    this.mUIItem8AF085B74DFEFDD3Window = new UIItem8AF085B74DFEFDD3Window();
                }
                return this.mUIItem8AF085B74DFEFDD3Window;
            }
        }
        
        public UIКопирование8AF085B74Window UIКопирование8AF085B74Window
        {
            get
            {
                if ((this.mUIКопирование8AF085B74Window == null))
                {
                    this.mUIКопирование8AF085B74Window = new UIКопирование8AF085B74Window();
                }
                return this.mUIКопирование8AF085B74Window;
            }
        }
        
        public UIItemWindow2 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow2();
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIEDoctrinaOCREditorv1Window mUIEDoctrinaOCREditorv1Window;
        
        private UIEDoctrinaOCREditorSeWindow mUIEDoctrinaOCREditorSeWindow;
        
        private UIВыполнениеприложенийWindow mUIВыполнениеприложенийWindow;
        
        private UIItem8AF085B74DFEFDD3Window mUIItem8AF085B74DFEFDD3Window;
        
        private UIКопирование8AF085B74Window mUIКопирование8AF085B74Window;
        
        private UIItemWindow2 mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "10.0.40219.415")]
    public class UIEDoctrinaOCREditorv1Window : WinWindow
    {
        
        public UIEDoctrinaOCREditorv1Window()
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.Name] = "eDoctrina OCR Editor v. 1.0.0.381 (D:\\E\\Visual_C#\\2008 Проекты C#\\svn\\eDoctrinaOc" +
                "r\\Release)";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("eDoctrina OCR Editor v. 1.0.0.381 (D:\\E\\Visual_C#\\2008 Проекты C#\\svn\\eDoctrinaOc" +
                    "r\\Release)");
            this.WindowTitles.Add("eDoctrina OCR Editor v. 1.0.0.381 (D:\\E\\Visual_C#\\2008 Проекты C#\\svn\\eDoctrinaOc" +
                    "r\\Release) X: 78 Y: 1991");
            this.WindowTitles.Add("eDoctrina OCR Editor v. 1.0.0.381 (D:\\E\\Visual_C#\\2008 Проекты C#\\svn\\eDoctrinaOc" +
                    "r\\Release) X: 20 Y: 1965");
            this.WindowTitles.Add("eDoctrina OCR Editor v. 1.0.0.381 (D:\\E\\Visual_C#\\2008 Проекты C#\\svn\\eDoctrinaOc" +
                    "r\\Release) X: 33 Y: 2024");
            this.WindowTitles.Add("eDoctrina OCR Editor v. 1.0.0.381 (D:\\E\\Visual_C#\\2008 Проекты C#\\svn\\eDoctrinaOc" +
                    "r\\Release) X: 2811 Y: 4086");
            #endregion
        }
        
        #region Properties
        public UIMainMenuMenuBar UIMainMenuMenuBar
        {
            get
            {
                if ((this.mUIMainMenuMenuBar == null))
                {
                    this.mUIMainMenuMenuBar = new UIMainMenuMenuBar(this);
                }
                return this.mUIMainMenuMenuBar;
            }
        }
        
        public UIRbtnRotateWindow UIRbtnRotateWindow
        {
            get
            {
                if ((this.mUIRbtnRotateWindow == null))
                {
                    this.mUIRbtnRotateWindow = new UIRbtnRotateWindow(this);
                }
                return this.mUIRbtnRotateWindow;
            }
        }
        
        public UIPictureBox1Window UIPictureBox1Window
        {
            get
            {
                if ((this.mUIPictureBox1Window == null))
                {
                    this.mUIPictureBox1Window = new UIPictureBox1Window(this);
                }
                return this.mUIPictureBox1Window;
            }
        }
        
        public UIRestoreWindow UIRestoreWindow
        {
            get
            {
                if ((this.mUIRestoreWindow == null))
                {
                    this.mUIRestoreWindow = new UIRestoreWindow(this);
                }
                return this.mUIRestoreWindow;
            }
        }
        
        public UIRbtnCutWindow UIRbtnCutWindow
        {
            get
            {
                if ((this.mUIRbtnCutWindow == null))
                {
                    this.mUIRbtnCutWindow = new UIRbtnCutWindow(this);
                }
                return this.mUIRbtnCutWindow;
            }
        }
        
        public UIEDoctrinaOCREditorv1TitleBar UIEDoctrinaOCREditorv1TitleBar
        {
            get
            {
                if ((this.mUIEDoctrinaOCREditorv1TitleBar == null))
                {
                    this.mUIEDoctrinaOCREditorv1TitleBar = new UIEDoctrinaOCREditorv1TitleBar(this);
                }
                return this.mUIEDoctrinaOCREditorv1TitleBar;
            }
        }
        
        public UIVerifyWindow UIVerifyWindow
        {
            get
            {
                if ((this.mUIVerifyWindow == null))
                {
                    this.mUIVerifyWindow = new UIVerifyWindow(this);
                }
                return this.mUIVerifyWindow;
            }
        }
        
        public UIStatusStrip1Window UIStatusStrip1Window
        {
            get
            {
                if ((this.mUIStatusStrip1Window == null))
                {
                    this.mUIStatusStrip1Window = new UIStatusStrip1Window(this);
                }
                return this.mUIStatusStrip1Window;
            }
        }
        #endregion
        
        #region Fields
        private UIMainMenuMenuBar mUIMainMenuMenuBar;
        
        private UIRbtnRotateWindow mUIRbtnRotateWindow;
        
        private UIPictureBox1Window mUIPictureBox1Window;
        
        private UIRestoreWindow mUIRestoreWindow;
        
        private UIRbtnCutWindow mUIRbtnCutWindow;
        
        private UIEDoctrinaOCREditorv1TitleBar mUIEDoctrinaOCREditorv1TitleBar;
        
        private UIVerifyWindow mUIVerifyWindow;
        
        private UIStatusStrip1Window mUIStatusStrip1Window;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "10.0.40219.415")]
    public class UIMainMenuMenuBar : WinMenuBar
    {
        
        public UIMainMenuMenuBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinMenu.PropertyNames.Name] = "menuStrip1";
            this.WindowTitles.Add("eDoctrina OCR Editor v. 1.0.0.381 (D:\\E\\Visual_C#\\2008 Проекты C#\\svn\\eDoctrinaOc" +
                    "r\\Release)");
            #endregion
        }
        
        #region Properties
        public UIFileMenuItem UIFileMenuItem
        {
            get
            {
                if ((this.mUIFileMenuItem == null))
                {
                    this.mUIFileMenuItem = new UIFileMenuItem(this);
                }
                return this.mUIFileMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private UIFileMenuItem mUIFileMenuItem;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "10.0.40219.415")]
    public class UIFileMenuItem : WinMenuItem
    {
        
        public UIFileMenuItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinMenuItem.PropertyNames.Name] = "File";
            this.WindowTitles.Add("eDoctrina OCR Editor v. 1.0.0.381 (D:\\E\\Visual_C#\\2008 Проекты C#\\svn\\eDoctrinaOc" +
                    "r\\Release)");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UISettingsMenuItem
        {
            get
            {
                if ((this.mUISettingsMenuItem == null))
                {
                    this.mUISettingsMenuItem = new WinMenuItem(this);
                    #region Условия поиска
                    this.mUISettingsMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Settings";
                    this.mUISettingsMenuItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUISettingsMenuItem.WindowTitles.Add("eDoctrina OCR Editor v. 1.0.0.381 (D:\\E\\Visual_C#\\2008 Проекты C#\\svn\\eDoctrinaOc" +
                            "r\\Release)");
                    #endregion
                }
                return this.mUISettingsMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUISettingsMenuItem;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "10.0.40219.415")]
    public class UIRbtnRotateWindow : WinWindow
    {
        
        public UIRbtnRotateWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "rbtnRotate";
            this.WindowTitles.Add("eDoctrina OCR Editor v. 1.0.0.381 (D:\\E\\Visual_C#\\2008 Проекты C#\\svn\\eDoctrinaOc" +
                    "r\\Release)");
            #endregion
        }
        
        #region Properties
        public WinRadioButton UIRbtnRotateRadioButton
        {
            get
            {
                if ((this.mUIRbtnRotateRadioButton == null))
                {
                    this.mUIRbtnRotateRadioButton = new WinRadioButton(this);
                    #region Условия поиска
                    this.mUIRbtnRotateRadioButton.WindowTitles.Add("eDoctrina OCR Editor v. 1.0.0.381 (D:\\E\\Visual_C#\\2008 Проекты C#\\svn\\eDoctrinaOc" +
                            "r\\Release)");
                    #endregion
                }
                return this.mUIRbtnRotateRadioButton;
            }
        }
        #endregion
        
        #region Fields
        private WinRadioButton mUIRbtnRotateRadioButton;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "10.0.40219.415")]
    public class UIPictureBox1Window : WinWindow
    {
        
        public UIPictureBox1Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "pictureBox1";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "7";
            this.WindowTitles.Add("eDoctrina OCR Editor v. 1.0.0.381 (D:\\E\\Visual_C#\\2008 Проекты C#\\svn\\eDoctrinaOc" +
                    "r\\Release) X: 78 Y: 1991");
            this.WindowTitles.Add("eDoctrina OCR Editor v. 1.0.0.381 (D:\\E\\Visual_C#\\2008 Проекты C#\\svn\\eDoctrinaOc" +
                    "r\\Release) X: 20 Y: 1965");
            this.WindowTitles.Add("eDoctrina OCR Editor v. 1.0.0.381 (D:\\E\\Visual_C#\\2008 Проекты C#\\svn\\eDoctrinaOc" +
                    "r\\Release) X: 33 Y: 2024");
            #endregion
        }
        
        #region Properties
        public WinClient UIPictureBox1Client
        {
            get
            {
                if ((this.mUIPictureBox1Client == null))
                {
                    this.mUIPictureBox1Client = new WinClient(this);
                    #region Условия поиска
                    this.mUIPictureBox1Client.WindowTitles.Add("eDoctrina OCR Editor v. 1.0.0.381 (D:\\E\\Visual_C#\\2008 Проекты C#\\svn\\eDoctrinaOc" +
                            "r\\Release) X: 78 Y: 1991");
                    this.mUIPictureBox1Client.WindowTitles.Add("eDoctrina OCR Editor v. 1.0.0.381 (D:\\E\\Visual_C#\\2008 Проекты C#\\svn\\eDoctrinaOc" +
                            "r\\Release) X: 20 Y: 1965");
                    this.mUIPictureBox1Client.WindowTitles.Add("eDoctrina OCR Editor v. 1.0.0.381 (D:\\E\\Visual_C#\\2008 Проекты C#\\svn\\eDoctrinaOc" +
                            "r\\Release) X: 33 Y: 2024");
                    #endregion
                }
                return this.mUIPictureBox1Client;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIPictureBox1Client;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "10.0.40219.415")]
    public class UIRestoreWindow : WinWindow
    {
        
        public UIRestoreWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnRestore";
            this.WindowTitles.Add("eDoctrina OCR Editor v. 1.0.0.381 (D:\\E\\Visual_C#\\2008 Проекты C#\\svn\\eDoctrinaOc" +
                    "r\\Release)");
            #endregion
        }
        
        #region Properties
        public WinButton UIRestoreButton
        {
            get
            {
                if ((this.mUIRestoreButton == null))
                {
                    this.mUIRestoreButton = new WinButton(this);
                    #region Условия поиска
                    this.mUIRestoreButton.SearchProperties[WinButton.PropertyNames.Name] = "Restore";
                    this.mUIRestoreButton.WindowTitles.Add("eDoctrina OCR Editor v. 1.0.0.381 (D:\\E\\Visual_C#\\2008 Проекты C#\\svn\\eDoctrinaOc" +
                            "r\\Release)");
                    #endregion
                }
                return this.mUIRestoreButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIRestoreButton;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "10.0.40219.415")]
    public class UIRbtnCutWindow : WinWindow
    {
        
        public UIRbtnCutWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "rbtnCut";
            this.WindowTitles.Add("eDoctrina OCR Editor v. 1.0.0.381 (D:\\E\\Visual_C#\\2008 Проекты C#\\svn\\eDoctrinaOc" +
                    "r\\Release)");
            #endregion
        }
        
        #region Properties
        public WinRadioButton UIRbtnCutRadioButton
        {
            get
            {
                if ((this.mUIRbtnCutRadioButton == null))
                {
                    this.mUIRbtnCutRadioButton = new WinRadioButton(this);
                    #region Условия поиска
                    this.mUIRbtnCutRadioButton.WindowTitles.Add("eDoctrina OCR Editor v. 1.0.0.381 (D:\\E\\Visual_C#\\2008 Проекты C#\\svn\\eDoctrinaOc" +
                            "r\\Release)");
                    #endregion
                }
                return this.mUIRbtnCutRadioButton;
            }
        }
        #endregion
        
        #region Fields
        private WinRadioButton mUIRbtnCutRadioButton;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "10.0.40219.415")]
    public class UIEDoctrinaOCREditorv1TitleBar : WinTitleBar
    {
        
        public UIEDoctrinaOCREditorv1TitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.WindowTitles.Add("eDoctrina OCR Editor v. 1.0.0.381 (D:\\E\\Visual_C#\\2008 Проекты C#\\svn\\eDoctrinaOc" +
                    "r\\Release)");
            #endregion
        }
        
        #region Properties
        public WinButton UIСвернутьButton
        {
            get
            {
                if ((this.mUIСвернутьButton == null))
                {
                    this.mUIСвернутьButton = new WinButton(this);
                    #region Условия поиска
                    this.mUIСвернутьButton.SearchProperties[WinButton.PropertyNames.Name] = "Свернуть";
                    this.mUIСвернутьButton.WindowTitles.Add("eDoctrina OCR Editor v. 1.0.0.381 (D:\\E\\Visual_C#\\2008 Проекты C#\\svn\\eDoctrinaOc" +
                            "r\\Release)");
                    #endregion
                }
                return this.mUIСвернутьButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIСвернутьButton;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "10.0.40219.415")]
    public class UIVerifyWindow : WinWindow
    {
        
        public UIVerifyWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "VerifyButton";
            this.WindowTitles.Add("eDoctrina OCR Editor v. 1.0.0.381 (D:\\E\\Visual_C#\\2008 Проекты C#\\svn\\eDoctrinaOc" +
                    "r\\Release)");
            #endregion
        }
        
        #region Properties
        public WinButton UIVerifyButton
        {
            get
            {
                if ((this.mUIVerifyButton == null))
                {
                    this.mUIVerifyButton = new WinButton(this);
                    #region Условия поиска
                    this.mUIVerifyButton.SearchProperties[WinButton.PropertyNames.Name] = "Verify";
                    this.mUIVerifyButton.WindowTitles.Add("eDoctrina OCR Editor v. 1.0.0.381 (D:\\E\\Visual_C#\\2008 Проекты C#\\svn\\eDoctrinaOc" +
                            "r\\Release)");
                    #endregion
                }
                return this.mUIVerifyButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIVerifyButton;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "10.0.40219.415")]
    public class UIStatusStrip1Window : WinWindow
    {
        
        public UIStatusStrip1Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "statusStrip1";
            this.WindowTitles.Add("eDoctrina OCR Editor v. 1.0.0.381 (D:\\E\\Visual_C#\\2008 Проекты C#\\svn\\eDoctrinaOc" +
                    "r\\Release) X: 2811 Y: 4086");
            #endregion
        }
        
        #region Properties
        public WinStatusBar UIStatusStrip1StatusBar
        {
            get
            {
                if ((this.mUIStatusStrip1StatusBar == null))
                {
                    this.mUIStatusStrip1StatusBar = new WinStatusBar(this);
                    #region Условия поиска
                    this.mUIStatusStrip1StatusBar.SearchProperties[WinStatusBar.PropertyNames.Name] = "statusStrip1";
                    this.mUIStatusStrip1StatusBar.WindowTitles.Add("eDoctrina OCR Editor v. 1.0.0.381 (D:\\E\\Visual_C#\\2008 Проекты C#\\svn\\eDoctrinaOc" +
                            "r\\Release) X: 2811 Y: 4086");
                    #endregion
                }
                return this.mUIStatusStrip1StatusBar;
            }
        }
        #endregion
        
        #region Fields
        private WinStatusBar mUIStatusStrip1StatusBar;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "10.0.40219.415")]
    public class UIEDoctrinaOCREditorSeWindow : WinWindow
    {
        
        public UIEDoctrinaOCREditorSeWindow()
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.Name] = "eDoctrina OCR Editor Settings";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("eDoctrina OCR Editor Settings");
            #endregion
        }
        
        #region Properties
        public UISaveWindow UISaveWindow
        {
            get
            {
                if ((this.mUISaveWindow == null))
                {
                    this.mUISaveWindow = new UISaveWindow(this);
                }
                return this.mUISaveWindow;
            }
        }
        #endregion
        
        #region Fields
        private UISaveWindow mUISaveWindow;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "10.0.40219.415")]
    public class UISaveWindow : WinWindow
    {
        
        public UISaveWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnSave";
            this.WindowTitles.Add("eDoctrina OCR Editor Settings");
            #endregion
        }
        
        #region Properties
        public WinButton UISaveButton
        {
            get
            {
                if ((this.mUISaveButton == null))
                {
                    this.mUISaveButton = new WinButton(this);
                    #region Условия поиска
                    this.mUISaveButton.SearchProperties[WinButton.PropertyNames.Name] = "Save";
                    this.mUISaveButton.WindowTitles.Add("eDoctrina OCR Editor Settings");
                    #endregion
                }
                return this.mUISaveButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUISaveButton;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "10.0.40219.415")]
    public class UIВыполнениеприложенийWindow : WinWindow
    {
        
        public UIВыполнениеприложенийWindow()
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Выполнение приложений";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "MSTaskSwWClass";
            this.WindowTitles.Add("Выполнение приложений");
            #endregion
        }
        
        #region Properties
        public UIВыполнениеприложенийToolBar UIВыполнениеприложенийToolBar
        {
            get
            {
                if ((this.mUIВыполнениеприложенийToolBar == null))
                {
                    this.mUIВыполнениеприложенийToolBar = new UIВыполнениеприложенийToolBar(this);
                }
                return this.mUIВыполнениеприложенийToolBar;
            }
        }
        #endregion
        
        #region Fields
        private UIВыполнениеприложенийToolBar mUIВыполнениеприложенийToolBar;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "10.0.40219.415")]
    public class UIВыполнениеприложенийToolBar : WinToolBar
    {
        
        public UIВыполнениеприложенийToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Выполнение приложений";
            this.WindowTitles.Add("Выполнение приложений");
            #endregion
        }
        
        #region Properties
        public WinButton UIItem8AF085B74DFEFDD3Button
        {
            get
            {
                if ((this.mUIItem8AF085B74DFEFDD3Button == null))
                {
                    this.mUIItem8AF085B74DFEFDD3Button = new WinButton(this);
                    #region Условия поиска
                    this.mUIItem8AF085B74DFEFDD3Button.SearchProperties[WinButton.PropertyNames.Name] = "8AF085B74DFEFDD3A9879FED71C160879A334FDB.tiff - FastStone";
                    this.mUIItem8AF085B74DFEFDD3Button.WindowTitles.Add("Выполнение приложений");
                    #endregion
                }
                return this.mUIItem8AF085B74DFEFDD3Button;
            }
        }
        
        public WinButton UISkypef_igor77Button
        {
            get
            {
                if ((this.mUISkypef_igor77Button == null))
                {
                    this.mUISkypef_igor77Button = new WinButton(this);
                    #region Условия поиска
                    this.mUISkypef_igor77Button.SearchProperties[WinButton.PropertyNames.Name] = "Skype™ - f_igor77";
                    this.mUISkypef_igor77Button.WindowTitles.Add("Выполнение приложений");
                    #endregion
                }
                return this.mUISkypef_igor77Button;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIItem8AF085B74DFEFDD3Button;
        
        private WinButton mUISkypef_igor77Button;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "10.0.40219.415")]
    public class UIItem8AF085B74DFEFDD3Window : WinWindow
    {
        
        public UIItem8AF085B74DFEFDD3Window()
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.Name] = "8AF085B74DFEFDD3A9879FED71C160879A334FDB.tiff  -  FastStone Image Viewer 4.8";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "FastStoneImageViewerMainForm";
            this.WindowTitles.Add("8AF085B74DFEFDD3A9879FED71C160879A334FDB.tiff  -  FastStone Image Viewer 4.8");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIItem8AF085B74DFEFDD3TitleBar UIItem8AF085B74DFEFDD3TitleBar
        {
            get
            {
                if ((this.mUIItem8AF085B74DFEFDD3TitleBar == null))
                {
                    this.mUIItem8AF085B74DFEFDD3TitleBar = new UIItem8AF085B74DFEFDD3TitleBar(this);
                }
                return this.mUIItem8AF085B74DFEFDD3TitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        
        private UIItem8AF085B74DFEFDD3TitleBar mUIItem8AF085B74DFEFDD3TitleBar;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "10.0.40219.415")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TListView";
            this.WindowTitles.Add("8AF085B74DFEFDD3A9879FED71C160879A334FDB.tiff  -  FastStone Image Viewer 4.8");
            #endregion
        }
        
        #region Properties
        public UIItemList UIItemList
        {
            get
            {
                if ((this.mUIItemList == null))
                {
                    this.mUIItemList = new UIItemList(this);
                }
                return this.mUIItemList;
            }
        }
        #endregion
        
        #region Fields
        private UIItemList mUIItemList;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "10.0.40219.415")]
    public class UIItemList : WinList
    {
        
        public UIItemList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.WindowTitles.Add("8AF085B74DFEFDD3A9879FED71C160879A334FDB.tiff  -  FastStone Image Viewer 4.8");
            #endregion
        }
        
        #region Properties
        public WinListItem UIItemListItem
        {
            get
            {
                if ((this.mUIItemListItem == null))
                {
                    this.mUIItemListItem = new WinListItem(this);
                    #region Условия поиска
                    this.mUIItemListItem.SearchProperties[WinListItem.PropertyNames.Name] = "          ";
                    this.mUIItemListItem.SearchProperties[WinListItem.PropertyNames.Instance] = "7";
                    this.mUIItemListItem.WindowTitles.Add("8AF085B74DFEFDD3A9879FED71C160879A334FDB.tiff  -  FastStone Image Viewer 4.8");
                    #endregion
                }
                return this.mUIItemListItem;
            }
        }
        #endregion
        
        #region Fields
        private WinListItem mUIItemListItem;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "10.0.40219.415")]
    public class UIItem8AF085B74DFEFDD3TitleBar : WinTitleBar
    {
        
        public UIItem8AF085B74DFEFDD3TitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.WindowTitles.Add("8AF085B74DFEFDD3A9879FED71C160879A334FDB.tiff  -  FastStone Image Viewer 4.8");
            #endregion
        }
        
        #region Properties
        public WinButton UIСвернутьButton
        {
            get
            {
                if ((this.mUIСвернутьButton == null))
                {
                    this.mUIСвернутьButton = new WinButton(this);
                    #region Условия поиска
                    this.mUIСвернутьButton.SearchProperties[WinButton.PropertyNames.Name] = "Свернуть";
                    this.mUIСвернутьButton.WindowTitles.Add("8AF085B74DFEFDD3A9879FED71C160879A334FDB.tiff  -  FastStone Image Viewer 4.8");
                    #endregion
                }
                return this.mUIСвернутьButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIСвернутьButton;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "10.0.40219.415")]
    public class UIКопирование8AF085B74Window : WinWindow
    {
        
        public UIКопирование8AF085B74Window()
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Копирование \"8AF085B74DFEFDD3A9879FED71C160879A334FDB.tiff\" в папку";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TCopyMoveFolder";
            this.WindowTitles.Add("Копирование \"8AF085B74DFEFDD3A9879FED71C160879A334FDB.tiff\" в папку");
            #endregion
        }
        
        #region Properties
        public UIItemWindow1 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow1(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow1 mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "10.0.40219.415")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TListView";
            this.WindowTitles.Add("Копирование \"8AF085B74DFEFDD3A9879FED71C160879A334FDB.tiff\" в папку");
            #endregion
        }
        
        #region Properties
        public WinList UIItemList
        {
            get
            {
                if ((this.mUIItemList == null))
                {
                    this.mUIItemList = new WinList(this);
                    #region Условия поиска
                    this.mUIItemList.WindowTitles.Add("Копирование \"8AF085B74DFEFDD3A9879FED71C160879A334FDB.tiff\" в папку");
                    #endregion
                }
                return this.mUIItemList;
            }
        }
        #endregion
        
        #region Fields
        private WinList mUIItemList;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "10.0.40219.415")]
    public class UIItemWindow2 : WinWindow
    {
        
        public UIItemWindow2()
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Рабочий стол";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32769";
            #endregion
        }
        
        #region Properties
        public UIItemWindow11 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow11(this);
                }
                return this.mUIItemWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow11 mUIItemWindow1;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "10.0.40219.415")]
    public class UIItemWindow11 : WinWindow
    {
        
        public UIItemWindow11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TImageEnView";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            #endregion
        }
        
        #region Properties
        public WinClient UIРабочийстолClient
        {
            get
            {
                if ((this.mUIРабочийстолClient == null))
                {
                    this.mUIРабочийстолClient = new WinClient(this);
                }
                return this.mUIРабочийстолClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIРабочийстолClient;
        #endregion
    }
}
